name: pystan
channels:
  - defaults
dependencies:
  - cython=0.29.32
  - libpython=2.2
  - m2w64-toolchain=5.3.0
  - matplotlib=3.5.3
  - msys2-conda-epoch=20160418
  - numpy=1.21.6
  - pandas=1.3.5
  - pystan=2.19.1.1
  - python=3.7.12
  - scipy=1.7.3
  - scikit-learn